-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.attachments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  entity_type text NOT NULL CHECK (entity_type = ANY (ARRAY['milestone'::text, 'event'::text, 'goal'::text])),
  entity_id uuid NOT NULL,
  file_name text NOT NULL,
  file_type text,
  file_size integer,
  storage_path text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attachments_pkey PRIMARY KEY (id),
  CONSTRAINT attachments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.calendar_event_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  calendar_event_id uuid NOT NULL,
  goal_id uuid,
  phase_id uuid,
  milestone_id uuid,
  task_id uuid,
  subtask_id uuid,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT calendar_event_items_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_event_items_calendar_event_id_fkey FOREIGN KEY (calendar_event_id) REFERENCES public.calendar_events(id),
  CONSTRAINT calendar_event_items_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(id),
  CONSTRAINT calendar_event_items_phase_id_fkey FOREIGN KEY (phase_id) REFERENCES public.phases(id),
  CONSTRAINT calendar_event_items_milestone_id_fkey FOREIGN KEY (milestone_id) REFERENCES public.milestones(id),
  CONSTRAINT calendar_event_items_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT calendar_event_items_subtask_id_fkey FOREIGN KEY (subtask_id) REFERENCES public.subtasks(id)
);
CREATE TABLE public.calendar_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  summary text NOT NULL,
  description text,
  location text,
  start_datetime timestamp with time zone NOT NULL,
  end_datetime timestamp with time zone NOT NULL,
  start_date date,
  end_date date,
  timezone text DEFAULT 'UTC'::text,
  is_all_day boolean DEFAULT false,
  color_id text,
  source text DEFAULT 'ambitionos'::text CHECK (source = ANY (ARRAY['ambitionos'::text, 'google_calendar'::text, 'manual'::text, 'recurring_instance'::text])),
  sync_status USER-DEFINED DEFAULT 'local_only'::sync_status,
  external_event_id text,
  goal_id uuid,
  phase_id uuid,
  milestone_id uuid,
  event_type USER-DEFINED DEFAULT 'task'::event_type,
  priority USER-DEFINED DEFAULT 'medium'::priority_level,
  energy_cost USER-DEFINED DEFAULT 'medium'::priority_level,
  status USER-DEFINED DEFAULT 'scheduled'::event_status,
  rationale text,
  reschedule_count integer DEFAULT 0,
  original_start_datetime timestamp with time zone,
  recurrence_rule jsonb,
  is_recurring boolean DEFAULT false,
  recurring_event_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  roadmap_task_id uuid,
  allocation_type USER-DEFINED DEFAULT 'manual'::allocation_type,
  session_index integer,
  total_sessions integer,
  duration_minutes integer,
  effort_minutes_allocated integer,
  completed_at timestamp with time zone,
  skipped_reason text,
  ai_metadata jsonb DEFAULT '{}'::jsonb,
  task_id uuid,
  subtask_id uuid,
  difficulty integer DEFAULT 3 CHECK (difficulty >= 1 AND difficulty <= 5),
  is_locked boolean DEFAULT false,
  cognitive_type USER-DEFINED DEFAULT 'shallow_work'::cognitive_type,
  ai_confidence_score integer DEFAULT 0 CHECK (ai_confidence_score >= 0 AND ai_confidence_score <= 100),
  scheduling_reasoning text,
  CONSTRAINT calendar_events_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT calendar_events_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(id),
  CONSTRAINT calendar_events_phase_id_fkey FOREIGN KEY (phase_id) REFERENCES public.phases(id),
  CONSTRAINT calendar_events_milestone_id_fkey FOREIGN KEY (milestone_id) REFERENCES public.milestones(id),
  CONSTRAINT calendar_events_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT calendar_events_subtask_id_fkey FOREIGN KEY (subtask_id) REFERENCES public.subtasks(id)
);
CREATE TABLE public.chat_action_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message_id uuid,
  user_id uuid NOT NULL,
  session_id uuid,
  action_type text NOT NULL,
  target_type text,
  target_id uuid,
  target_title text,
  action_input jsonb NOT NULL,
  action_output jsonb,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'executed'::text, 'failed'::text, 'cancelled'::text, 'rolled_back'::text])),
  requires_confirmation boolean DEFAULT false,
  confirmed_at timestamp with time zone,
  confirmation_message_id uuid,
  error_message text,
  retry_count integer DEFAULT 0,
  is_undoable boolean DEFAULT false,
  undo_data jsonb,
  undone_at timestamp with time zone,
  undone_by_action_id uuid,
  requested_at timestamp with time zone DEFAULT now(),
  executed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_action_log_pkey PRIMARY KEY (id),
  CONSTRAINT chat_action_log_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.chat_messages(id),
  CONSTRAINT chat_action_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT chat_action_log_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id),
  CONSTRAINT chat_action_log_confirmation_message_id_fkey FOREIGN KEY (confirmation_message_id) REFERENCES public.chat_messages(id),
  CONSTRAINT chat_action_log_undone_by_action_id_fkey FOREIGN KEY (undone_by_action_id) REFERENCES public.chat_action_log(id)
);
CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text])),
  content text NOT NULL,
  function_calls jsonb DEFAULT '[]'::jsonb,
  action_results jsonb DEFAULT '[]'::jsonb,
  thinking text,
  pending_confirmation jsonb,
  tokens_input integer,
  tokens_output integer,
  latency_ms integer,
  is_error boolean DEFAULT false,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id)
);
CREATE TABLE public.chat_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text,
  started_at timestamp with time zone DEFAULT now(),
  last_message_at timestamp with time zone DEFAULT now(),
  message_count integer DEFAULT 0,
  conversation_state jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  ended_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.goals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  original_input text,
  category USER-DEFINED NOT NULL,
  timeline text,
  estimated_weeks integer,
  strategy_overview text,
  critical_gaps ARRAY,
  overview_generated boolean DEFAULT false,
  priority_weight numeric DEFAULT 50,
  behavior_plan jsonb DEFAULT '{}'::jsonb,
  risk_level text DEFAULT 'low'::text,
  risk_acknowledged_at timestamp with time zone,
  current_phase_index integer DEFAULT 0,
  overall_progress numeric DEFAULT 0 CHECK (overall_progress >= 0::numeric AND overall_progress <= 100::numeric),
  status USER-DEFINED DEFAULT 'planning'::goal_status,
  is_scheduled boolean DEFAULT false,
  preferred_time text DEFAULT 'flexible'::text CHECK (preferred_time = ANY (ARRAY['morning'::text, 'afternoon'::text, 'evening'::text, 'flexible'::text])),
  frequency integer DEFAULT 3 CHECK (frequency >= 1 AND frequency <= 7),
  duration integer DEFAULT 60 CHECK (duration >= 15 AND duration <= 180),
  energy_cost USER-DEFINED DEFAULT 'medium'::priority_level,
  preferred_days ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT goals_pkey PRIMARY KEY (id),
  CONSTRAINT goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.history_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  goal_id uuid,
  event_type text NOT NULL,
  details jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT history_entries_pkey PRIMARY KEY (id),
  CONSTRAINT history_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT history_entries_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(id)
);
CREATE TABLE public.milestones (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phase_id uuid NOT NULL,
  goal_id uuid NOT NULL,
  user_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  user_notes text,
  display_order integer DEFAULT 0,
  target_week integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT milestones_pkey PRIMARY KEY (id),
  CONSTRAINT milestones_phase_id_fkey FOREIGN KEY (phase_id) REFERENCES public.phases(id),
  CONSTRAINT milestones_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(id),
  CONSTRAINT milestones_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.phases (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  goal_id uuid NOT NULL,
  user_id uuid NOT NULL,
  phase_number integer NOT NULL CHECK (phase_number > 0),
  title text NOT NULL,
  description text,
  start_week integer NOT NULL,
  end_week integer NOT NULL,
  estimated_duration text,
  focus ARRAY,
  status USER-DEFINED DEFAULT 'upcoming'::phase_status,
  progress numeric DEFAULT 0 CHECK (progress >= 0::numeric AND progress <= 100::numeric),
  is_scheduled boolean DEFAULT false,
  coach_advice text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT phases_pkey PRIMARY KEY (id),
  CONSTRAINT phases_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(id),
  CONSTRAINT phases_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  name text NOT NULL DEFAULT ''::text,
  role text DEFAULT ''::text,
  role_context text,
  bio text,
  avatar_url text,
  chronotype USER-DEFINED DEFAULT 'flexible'::chronotype,
  work_style USER-DEFINED DEFAULT 'flow'::work_style,
  energy_level USER-DEFINED DEFAULT 'balanced'::energy_level,
  onboarding_completed boolean DEFAULT false,
  onboarding_step integer DEFAULT 0,
  timezone text DEFAULT 'UTC'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_preferences jsonb DEFAULT '{"working_hours": {"end": "17:00", "start": "09:00"}, "protected_times": [], "deep_work_limit_hours": 4, "break_frequency_minutes": 90}'::jsonb,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.subtasks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  milestone_id uuid NOT NULL,
  user_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  is_manual boolean DEFAULT false,
  is_strikethrough boolean DEFAULT false,
  strikethrough_reason text,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  task_id uuid,
  CONSTRAINT subtasks_pkey PRIMARY KEY (id),
  CONSTRAINT subtasks_milestone_id_fkey FOREIGN KEY (milestone_id) REFERENCES public.milestones(id),
  CONSTRAINT subtasks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT subtasks_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  milestone_id uuid NOT NULL,
  phase_id uuid,
  goal_id uuid,
  user_id uuid,
  title character varying NOT NULL,
  description text,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  is_strikethrough boolean DEFAULT false,
  strikethrough_reason text,
  start_day integer,
  end_day integer,
  duration_days integer,
  times_per_week integer DEFAULT 1,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  difficulty integer DEFAULT 3 CHECK (difficulty >= 1 AND difficulty <= 5),
  cognitive_type USER-DEFINED DEFAULT 'shallow_work'::cognitive_type,
  estimated_minutes integer DEFAULT 60,
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_milestone_id_fkey FOREIGN KEY (milestone_id) REFERENCES public.milestones(id),
  CONSTRAINT tasks_phase_id_fkey FOREIGN KEY (phase_id) REFERENCES public.phases(id),
  CONSTRAINT tasks_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(id),
  CONSTRAINT tasks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.time_blocks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  block_type USER-DEFINED NOT NULL,
  days ARRAY NOT NULL CHECK (array_length(days, 1) > 0),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_flexible boolean DEFAULT false,
  week_pattern text DEFAULT 'default'::text,
  timezone text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT time_blocks_pkey PRIMARY KEY (id),
  CONSTRAINT time_blocks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.time_constraints (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  sleep_start time without time zone DEFAULT '22:30:00'::time without time zone,
  sleep_end time without time zone DEFAULT '06:30:00'::time without time zone,
  peak_start time without time zone DEFAULT '09:00:00'::time without time zone,
  peak_end time without time zone DEFAULT '12:00:00'::time without time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT time_constraints_pkey PRIMARY KEY (id),
  CONSTRAINT time_constraints_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.time_exceptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_blocked boolean DEFAULT true,
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT time_exceptions_pkey PRIMARY KEY (id),
  CONSTRAINT time_exceptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
